---
- hosts: all
  become: yes
  tasks:
    - name: Install required packages for Debian/Ubuntu
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker from default repositories (Ubuntu)
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Python pip for Debian/Ubuntu
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker project directory exists on remote nodes
      file:
        path: ~/docker_project/website/
        state: directory
        mode: '0755'

    - name: Copy website files from workstation to remote nodes
      copy:
        src: /home/qfmgayao/activities/CPE212_FinalProject/website/
        dest: ~/docker_project/website/
        mode: '0644'
