---
- hosts: all
  become: yes
  tasks:
    - name: Install required packages for Debian/Ubuntu
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker from default repositories (Ubuntu)
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Python pip for Debian/Ubuntu
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Copy the Dockerfile to remote node
      ansible.builtin.copy:
        src: /home/qfmgayao/activities/CPE212_FinalProject/
        dest: /home/qfmgayao/docker_project/
        owner: remote_user
        group: remote_user
        mode: '0644'

    - name: Build Docker image on the remote node
      docker_image:
        name: my_website_image
        build:
          path: /home/remote_user/  # This path should be where the Dockerfile and website folder are
        source: build
        state: present

    - name: Run Docker container to serve website
      docker_container:
        name: website_container
        image: my_website_image
        state: started
        ports:
          - "80:80"  # Expose port 80 (HTTP)
        volumes:
          - /home/remote_user/website:/usr/share/nginx/html:ro  # Mount the website folder inside the container
        restart_policy: unless-stopped
