- name: Setup Dockerfile directory and copy Dockerfile
  hosts: all
  become: true
  tasks:
    - name: Ensure docker_project directory exists
      file:
        path: /home/qfmgayao/docker_project
        state: directory

    - name: Copy Dockerfile to docker_project
      copy:
        src: /home/qfmgayao/activities/CPE212_FinalProject/Dockerfile
        dest: /home/qfmgayao/docker_project/Dockerfile
        owner: root
        group: root
        mode: '0644'

